plugins {
    id 'java-gradle-plugin'
}

group = 'net.lopymine.mossyplugin'
version = '3.60.0-patpat.1'

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.kikugie.dev/releases' }
    maven { url = 'https://maven.kikugie.dev/snapshots' }
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
    gradlePluginPortal()
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    implementation 'dev.kikugie.stonecutter:dev.kikugie.stonecutter.gradle.plugin:0.9'
    implementation 'me.modmuss50.mod-publish-plugin:me.modmuss50.mod-publish-plugin.gradle.plugin:0.7.4'
    implementation 'dev.kikugie.fletching-table:dev.kikugie.fletching-table.gradle.plugin:0.1.0-alpha.17'
    implementation 'fabric-loom:fabric-loom.gradle.plugin:1.17.21'
    implementation 'net.neoforged.moddev:net.neoforged.moddev.gradle.plugin:2.0.147'
    implementation 'net.neoforged.gradle.userdev:net.neoforged.gradle.userdev.gradle.plugin:7.1.38'
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin:1.0.0'
}

gradlePlugin {
    plugins {
        ['settings', 'stonecutter', 'core'].each { module ->
            create(module) {
                id = "net.lopymine.mossy-plugin-${module}"
                implementationClass = "net.lopymine.mossyplugin.${module}.MossyPlugin${module.capitalize()}"
            }
        }
    }
}
